# Dockerfile
FROM node:22.14.0 AS builder

WORKDIR /app

# Recebe as variáveis no build
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WHATSAPP_PHONE
ARG NEXT_PUBLIC_WHATSAPP_URL
ARG NEXT_PUBLIC_API_TRACKSITEVISIT
ARG NEXT_PUBLIC_API_TRACKSTARTFREECLICK
ARG NEXT_PUBLIC_API_TRACKSCHEDULEDEMOCLICK
ARG NEXT_PUBLIC_API_TRACKSCHEDULEQUESTIONCLICK
ARG NEXT_PUBLIC_API_REGISTERCONTACT

# Exporta como env para o build do Next.js
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_WHATSAPP_PHONE=$NEXT_PUBLIC_WHATSAPP_PHONE
ENV NEXT_PUBLIC_WHATSAPP_URL=$NEXT_PUBLIC_WHATSAPP_URL
ENV NEXT_PUBLIC_API_TRACKSITEVISIT=$NEXT_PUBLIC_API_TRACKSITEVISIT
ENV NEXT_PUBLIC_API_TRACKSTARTFREECLICK=$NEXT_PUBLIC_API_TRACKSTARTFREECLICK
ENV NEXT_PUBLIC_API_TRACKSCHEDULEDEMOCLICK=$NEXT_PUBLIC_API_TRACKSCHEDULEDEMOCLICK
ENV NEXT_PUBLIC_API_TRACKSCHEDULEQUESTIONCLICK=$NEXT_PUBLIC_API_TRACKSCHEDULEQUESTIONCLICK
ENV NEXT_PUBLIC_API_REGISTERCONTACT=$NEXT_PUBLIC_API_REGISTERCONTACT

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---- Runtime container ----
FROM node:22.14.0

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "start"]
